CREATE PROCEDURE USP_CARGA_STG_RESERVA
AS

-- CRIA TABELA CASO NÃO EXISTA

IF OBJECT_ID('STG_RESERVAS') IS NULL
BEGIN
	CREATE TABLE STG_RESERVAS
	(
	   ID_RESERVA      NUMERIC(15)
	 , ID_CLIENTE      NUMERIC(15)
	 , NOME_CLIENTE	   VARCHAR(60)
	 , CPF             VARCHAR(14)
	 , DATA_NASCIMENTO DATE	 
	)

END

-- LIMPA TABELA STG_CLIENTES

TRUNCATE TABLE STG_RESERVAS


-- POPULA STAGE AREA

INSERT INTO STG_RESERVAS
(
   ID_RESERVA
 , ID_CLIENTE
 , NOME_CLIENTE
 , CPF
 , DATA_NASCIMENTO
)

SELECT A.ID_RESERVA
	 , A.ID_CLIENTE
	 , B.NOME_CLIENTE
	 , B.CPF
	 , B.DATA_NASCIMENTO	 
  FROM LIVRARIA_PROD.DBO.RESERVAS                A
  LEFT JOIN LIVRARIA_PROD.DBO.CLIENTES_LIVRARIA  B ON A.ID_CLIENTE = B.ID_CLIENTE


