CREATE PROCEDURE USP_CARGA_STG_LIVRO

 AS


-- CRIA TABELA CASO NÃO EXISTA

IF OBJECT_ID('STG_LIVROS') IS NULL
BEGIN
	CREATE TABLE STG_LIVROS
	(
	   ID_LIVRO      NUMERIC(15)
	 , NOME_LIVRO    VARCHAR(200)
	 , NOME_EDITORA  VARCHAR (60)
	 , NOME_AUTOR    VARCHAR(60)	
	)

END

-- LIMPA TABELA STG_LIVROS

TRUNCATE TABLE STG_LIVROS


-- POPULA STAGE AREA

INSERT INTO STG_LIVROS
(
   ID_LIVRO
 , NOME_LIVRO
 , NOME_EDITORA
 , NOME_AUTOR
)

   SELECT A.ID_LIVRO
   	    , A.NOME_LIVRO
   	    , B.NOME_EDITORA
   	    , C.NOME_AUTOR
     FROM LIVRARIA_PROD.DBO.LIVROS   A 
LEFT JOIN LIVRARIA_PROD.DBO.EDITORAS B ON A.ID_EDITORA = B.ID_EDITORA
LEFT JOIN LIVRARIA_PROD.DBO.AUTORES  C ON A.ID_AUTOR   = C.ID_AUTOR
