CREATE PROCEDURE USP_CARGA_STG_LIVRARIA ( @INCREMENTAL BIT )

AS

/*
@INCREMENTAL = 0 ---> CARGA FULL
@INCREMENTAL = 1 ---> CARGA INCREMENTAL
*/

   
-- CRIA TABELA CASO NÃO EXISTA

IF OBJECT_ID('STG_LIVRARIA') IS NULL

BEGIN
	CREATE TABLE STG_LIVRARIA
	(
	   ID_RESERVA_LIVRO NUMERIC(15)
	 , ID_RESERVA       NUMERIC(15)	 
	 , ID_LIVRO         NUMERIC(15)
	 , DATA_RESERVA     DATE
	 , DATA_RETIRADA    DATE
	 , DATA_PREVISAO    DATE
	 , DATA_DEVOLUCAO   DATE
	 , DIAS_RESERVA     NUMERIC(15)
	 , VALOR_LIVRO		MONEY
	)

END

-- LIMPA TABELA STG_LIVRARIA

TRUNCATE TABLE STG_LIVRARIA

-- POPULA STAGE AREA
INSERT INTO STG_LIVRARIA
(
   ID_RESERVA_LIVRO
 , ID_RESERVA 
 , ID_LIVRO
 , DATA_RESERVA
 , DATA_RETIRADA
 , DATA_PREVISAO
 , DATA_DEVOLUCAO
 , DIAS_RESERVA
 , VALOR_LIVRO
) 

  
   SELECT A.ID_RESERVA_LIVRO
		, A.ID_RESERVA		
		, A.ID_LIVRO
		, B.DATA_RESERVA
		, A.DATA_RETIRADA
		, A.DATA_PREVISAO
		, A.DATA_DEVOLUCAO
		, A.DIAS_RESERVA
		, C.VALOR			AS VALOR_LIVRO
     FROM LIVRARIA_PROD.DBO.RESERVA_LIVROS    A
LEFT JOIN LIVRARIA_PROD.DBO.RESERVAS          B ON A.ID_RESERVA = B.ID_RESERVA
LEFT JOIN LIVRARIA_PROD.DBO.LIVROS			  C ON A.ID_LIVRO   = C.ID_LIVRO
    WHERE B.DATA_RESERVA > CASE WHEN @INCREMENTAL = 1 THEN ( SELECT MAX(DATA_RESERVA) FROM LIVRARIA_DM.DBO.FATO_LIVRARIA )
								ELSE '01/01/1900'
						   END








