CREATE PROCEDURE USP_CARGA_DIM_LIVRO_02

AS

-- CRIA TABELA CASO NÃO EXISTA

IF OBJECT_ID('DIM_LIVROS') IS NULL

BEGIN
    
	CREATE TABLE DIM_LIVROS
	(	    
	   SK_LIVRO	     NUMERIC(15) PRIMARY KEY	 
	 , NOME_LIVRO	 VARCHAR(200)
	 , NOME_EDITORA  VARCHAR(60)
	 , NOME_AUTOR    VARCHAR(60)
	)

END


MERGE DIM_LIVROS D
USING LIVRARIA_STG.DBO.VW_DIM_LIVROS O ON D.SK_LIVRO = O.ID_LIVRO

-- QUANDO COINCIDIR

WHEN MATCHED THEN UPDATE
SET NOME_LIVRO   = O.NOME_LIVRO
  , NOME_EDITORA = O.NOME_EDITORA
  , NOME_AUTOR	 = O.NOME_AUTOR


-- QUANDO NÃO COINDIDIR

WHEN NOT MATCHED BY TARGET THEN INSERT
(
   SK_LIVRO	   
 , NOME_LIVRO	
 , NOME_EDITORA
 , NOME_AUTOR
)

 VALUES
(
   O.ID_LIVRO     
 , O.NOME_LIVRO	
 , O.NOME_EDITORA	
 , O.NOME_AUTOR	
);

