CREATE PROCEDURE USP_CARGA_FATO_LIVRARIA ( @INCREMENTAL BIT )

AS

-- CRIA TABELA CASO NÃO EXISTA

IF OBJECT_ID('FATO_LIVRARIA') IS NULL

BEGIN    

	CREATE TABLE FATO_LIVRARIA
	(
	   SK               NUMERIC(15)  
	 , SK_RESERVA	    NUMERIC(15) REFERENCES DIM_RESERVAS (SK_RESERVA)
	 , SK_LIVRO         NUMERIC(15) REFERENCES DIM_LIVROS   (SK_LIVRO)
	 , DATA_RESERVA     DATE
	 , DATA_RETIRADA	DATE
	 , DATA_PREVISAO	DATE
	 , DATA_DEVOLUCAO	DATE
	 , DIAS_RESERVA     NUMERIC(15)
	 , VALOR_LIVRO		MONEY
	)

END

-- LIMPA TABELA FATO

IF @INCREMENTAL = 0
BEGIN

	TRUNCATE TABLE FATO_LIVRARIA

END


-- POPULA FATO

INSERT INTO FATO_LIVRARIA

SELECT *
  FROM LIVRARIA_STG.DBO.VW_FATO_LIVRARIA 

 





